export {
  clearScreen,
  enterAlternateScreen,
  exitAlternateScreen,
  finalizeFrame,
  getPermissionPromptMaxScrollOffset,
  getTranscriptMaxScrollOffset,
  getTranscriptWindowSize,
  hideCursor,
  renderBanner,
  renderContextBadge,
  renderFooterBar,
  renderInputPrompt,
  renderPanel,
  renderPermissionPrompt,
  renderSlashMenu,
  renderStatusLine,
  renderToolPanel,
  renderTranscript,
  showCursor,
  extractSelectedText,
  renderTranscriptLines,
  moveCursorTo,
  enableCursorBlink,
  stringDisplayWidth,
  forceFullRepaint,
  renderFrame,
} from './tui/index.js'

export type { TranscriptEntry } from './tui/index.js'
export type { TranscriptSelection } from './tui/index.js'
